package com.ejemplo.app.webservice_db_mysql_json_php.interfaces;


import com.ejemplo.app.webservice_db_mysql_json_php.fragments.BienvenidaFragment;
import com.ejemplo.app.webservice_db_mysql_json_php.fragments.ConsultaListaUsuarioImagenUrlFragment;
import com.ejemplo.app.webservice_db_mysql_json_php.fragments.ConsultaUsuarioUrlFragment;
import com.ejemplo.app.webservice_db_mysql_json_php.fragments.ConsultarListaUsuariosFragment;
import com.ejemplo.app.webservice_db_mysql_json_php.fragments.ConsultarUsuarioFragment;
import com.ejemplo.app.webservice_db_mysql_json_php.fragments.ConsutarListausuarioImagenFragment;
import com.ejemplo.app.webservice_db_mysql_json_php.fragments.DesarrolladorFragment;
import com.ejemplo.app.webservice_db_mysql_json_php.fragments.RegistrarUsuarioFragment;

public interface IFragments extends BienvenidaFragment.OnFragmentInteractionListener, DesarrolladorFragment.OnFragmentInteractionListener,
        RegistrarUsuarioFragment.OnFragmentInteractionListener, ConsultarUsuarioFragment.OnFragmentInteractionListener,
        ConsultarListaUsuariosFragment.OnFragmentInteractionListener, ConsutarListausuarioImagenFragment.OnFragmentInteractionListener,
        ConsultaUsuarioUrlFragment.OnFragmentInteractionListener, ConsultaListaUsuarioImagenUrlFragment.OnFragmentInteractionListener{
}
